### ISSUE TITLE
希望有dfs详解，由浅入深的，谢谢

### ISSUE THREAD

**Issue by ChuwenLi** [SamZhangQingChuan/Editorials#6]
今天刚做的PDD笔试：
给定一组棍子长度，可以拼接，不能折断，问能否构成正方形（正方形有四条边，且四条边相等）
例子：
[1,1,1,1]
YES
[1,1,1,1,2,2,4,4]
YES
[1,2,3,2,1]
NO
我觉得是DFS问题，没做出来。谢谢。

**Comment by SamZhangQingChuan** [comment]
数据范围呢

**Comment by ChuwenLi** [comment]
木棍的数量1<=N<=20，长度1<=Li<=10000

**Comment by SamZhangQingChuan** [comment]
这个双向 bfs 就好了

**Comment by ChuwenLi** [comment]
OK,谢谢
