### ISSUE TITLE
求问算法题目

### ISSUE THREAD

**Issue by ChuwenLi** [SamZhangQingChuan/Editorials#7]
刚刚笔试完，凉了
n个数里面选k个，使得k个数相与结果最小
n<=40
1<=每个数字<=2^60
麻烦看下是什么思路，谢谢~

**Comment by qodjf** [comment]
trie。每一位尽量选 1。选不了 1，就把两个子树合并。

**Comment by ChuwenLi** [comment]
噢噢好的，谢谢

**Comment by SamZhangQingChuan** [comment]
@qodjf 这是最大吧

**Comment by qodjf** [comment]
> @qodjf 这是最大吧

哦哦。看错了

**Comment by xmyqsh** [comment]
minAnd(root, K) = min(minAnd(root->left, k) & minAnd(root->right, K - k))
https://gist.github.com/xmyqsh/b77fda9a966399a703110e8febfe5c9c
