### ISSUE TITLE
想看做题策略贴

### ISSUE THREAD

**Issue by helunxing** [SamZhangQingChuan/Editorials#8]
不知道是不是我记错了，印象中去年你的主页上有一个google doc的链接，里面写了诸如做题熟练度大于见题的心得之类的。

我看了那个文档看到挺有收获的，但现在找不到了，希望能在看到、学习。

谢谢楼主🙏

**Comment by SamZhangQingChuan** [comment]
那个写的不好。。。看 https://github.com/SamZhangQingChuan/Templates-for-Competitive-Programming/blob/master/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.md 吧

**Comment by helunxing** [comment]
> 那个写的不好。。。看 https://github.com/SamZhangQingChuan/Templates-for-Competitive-Programming/blob/master/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF.md 吧

谢老板指路
